### ISSUE TITLE
通知中心功能设计

### ISSUE THREAD

**Issue by hotlong** [steedos/creator#1287]
![image](https://user-images.githubusercontent.com/50353452/62991301-b0eea800-be81-11e9-9492-c06f88df30b2.png)

notifications 业务对象
```yml
name:
  label: 通知标题 
body:
  label: 通知描述
related_to:
  label: 相关记录
related_name:
 label: 记录标题
url:
  label: 相对链接
owner:
  label: 通知对象
is_read:
  label: 已读
created:
  label: 通知时间
```

示例
```yml
name: 庄建国给您安排了一个任务
related_to: 
  o: xxx
  ids: ["111"]
related_name: 开发推送通知功能
url: /app/-/contracts/:id
```

需要增加路由`/api/v4/notifications/:id/read `，第三方系统可以通过该路径重定向到我们的通知记录URL网页
