### ISSUE TITLE
发现modifyAllRecords/modifyCompanyRecords两个权限 一起配置的时候，取了modifyCompanyRecords的权限

### ISSUE THREAD

**Issue by yinlianghui** [steedos/creator#1425]
比如给admin同时设置两个权限为true。
```
  admin:
    allowCreate: true
    allowDelete: true
    allowEdit: true
    allowRead: true
    modifyAllRecords: true
    viewAllRecords: true
    modifyCompanyRecords: true
```
应该是个bug，这里指的是编辑按钮是否显示的权限，现象是取了modifyCompanyRecords权限后，编辑按钮未显示出来。
![image](https://user-images.githubusercontent.com/6219465/68755022-d89d0a00-0642-11ea-8041-abab9f9655a3.png)
