### ISSUE TITLE
CMS应用上线前考虑之前的附件写脚本兼容新的二合一版本

### ISSUE THREAD

**Issue by yinlianghui** [steedos/creator#1609]
关联任务：整合 steedos:cms 到二合一版本 #1602

主要附件有：
- [x] cms_posts文章的attachments字段，原来是关联到posts这个附件对象，改成了creator标准的enable_files附件方式
- [x] cms_sites站点的cover和avatar字段，原来是关联到avatars这个附件对象，改成了creator标准的type:avatar，估计creator中关联到的是avatar对象少了一个s  **此任务不需要写脚本同步数据，是同一张表**
- [x] cms_posts文章title改为name,author改为owner,space要加上
  - [x] 默认模板title改为name
  - [ ] 自定义模板title改为name
- [x] visibility直接去掉(过滤条件也不要了)
- [x] cms_categories 加上space字段，值取site.space
- [x] cms_posts文章的images字段需要转存到cfs.avatars  **不处理**
- [x] 重写post.images，Attachments 数据获取方式
- [ ] 站点的默认模板，及客户自定义模板中需要将 取图片的连接地址/posts 修改为 /files；取文件的连接地址(具体有没有需要看模板内容)/posts修改为 /files；images 获取方式调整，使用 images helper 获取，参数来post._id
  - [x] 默认模板
  - [ ] 自定义模板

以上需要确认附件保存的位置，以保证二合一版本中可以查看下载原来的老附件！

**Comment by baozhoutao** [comment]
cms_posts文章space要加上：cms_posts 记录的space如果没值，则取记录对应的site上的space值

**Comment by yinlianghui** [comment]
cms_posts文章的images字段需要维护，改为让用户手动上传附件（原来是触发器自动取附件中图片附件的id存入数据库的images字段中的），字段定义改为：
```
  images:
    label: 照片
    type: avatar
    multiple: true
    hidden: false
    omit: false
    is_wide: true
```
