### ISSUE TITLE
新建自定义列表视图，未添加显示的列时相关问题

### ISSUE THREAD

**Issue by yinlianghui** [steedos/creator#1645]
1.提示语问题，不应该提示`显示的列 must be an object`这种提示，不只是翻译不对，整个提示语就不对
2.`显示的列`字段必填星号没显示出来
3.当`显示的列`添加了空行的时候，可以新建成功视图，但是空列的视图显示很乱，最好能判断下空行也提示必填
![image](https://user-images.githubusercontent.com/6219465/76186697-1d5e3980-620e-11ea-894e-2ecc33c42ce8.png)
![image](https://user-images.githubusercontent.com/6219465/76192014-b6e01800-621b-11ea-8ed1-259e790add83.png)
![image](https://user-images.githubusercontent.com/6219465/76192158-163e2800-621c-11ea-98ea-400f27e2df37.png)

**Comment by yinlianghui** [comment]
- 1和2已处理，是因为整个grid字段没加required属性
- 3暂时未处理，是因为内核对gird字段的二级字段配置中的required属性（下面的`columns.$.field`字段）不会校验，暂不处理
```
  columns:
    label: 显示的列
    type: grid
    is_wide: true
    required: true
  columns.$:
    label: 显示的列
    blackbox: true
    type: object
  columns.$.field:
    label: 字段
    ...
    required: true
  columns.$.width:
    label: 宽度
    type: text
  columns.$.wrap:
   ...
```
