### ISSUE TITLE
所属单位字段company_id(s)在项目中通过继承的方式扩展后，位置不对

### ISSUE THREAD

**Issue by yinlianghui** [steedos/creator#1700]
- 优先看看能不能直接在继承的yml中修正该问题
- 不排除可能要改继承的源码（即继承后位置变了）

> 以下图二是原来的位置
![image](https://user-images.githubusercontent.com/6219465/77620788-178a8700-6f76-11ea-8898-68161c19f49b.png)

![image](https://user-images.githubusercontent.com/6219465/77620926-620c0380-6f76-11ea-909a-9d49e461de8b.png)

**Comment by yinlianghui** [comment]
该问题是继承的yml中只写了一个要重写的字段，造成该字段最终的排序变了造成的，重写的yml内容为:
```
extend: flows
fields:
  company_id:
    required: false
    omit: false
    hidden: false
```
